# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auxGibbs <- function(tab, di, om, eta, etaN, diToEta, lambda, lambdaN, diToLambda, etaM = 0L, auxM = 5L, alpha = 100.0, lambdaM = 0L, auxLambdaM = 1L, alphaLambda = 5.0, ijvals = 0L, verbose = 0L, dprior = 1.0, lambdaShape = 1.0, lambdaRate = 0.01) {
    .Call(`_cellTypeCompositions_auxGibbs`, tab, di, om, eta, etaN, diToEta, lambda, lambdaN, diToLambda, etaM, auxM, alpha, lambdaM, auxLambdaM, alphaLambda, ijvals, verbose, dprior, lambdaShape, lambdaRate)
}

sampleParms <- function(tab, di, om, dataToEta, dataToLambda, eta, etaM, lambda, lambdaM, dprior, lambdaAlpha, lambdaBeta, niter = 5L, verbose = 0L) {
    .Call(`_cellTypeCompositions_sampleParms`, tab, di, om, dataToEta, dataToLambda, eta, etaM, lambda, lambdaM, dprior, lambdaAlpha, lambdaBeta, niter, verbose)
}

